name: GitHub Contributions Snake

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Contribution Snake
        uses: paveloom/github-contribution-snake-action@v1
        with:
          repo: christopher-oyuga/Christopher-Oyuga
          github_token: ${{ secrets.GITHUB_TOKEN }}
